import NextHead from 'next/head'

const Head = () => {
  return (
    <NextHead>
      <title>Photo Gallery Maker</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </NextHead>
  )
}

export default Head
